[project]
name = "ecologits-calculator-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ecologits>=0.6.1",
    "pint>=0.24.4",
    "plotly>=6.0.0",
    "streamlit>=1.43.1",
]
