[project]
name = "ecologits-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ecologits>=0.7.3",
    "pint>=0.24.4",
    "plotly>=6.2.0",
    "streamlit>=1.47.1",
    "tiktoken>=0.9.0",
]
